version: '3.2'

services:
   db:
      image: mysql:5.7
      container_name: mysqlDB
      restart: always
      ports:
       - '127.0.0.1:4406:3306'
      volumes:
       - "/home/nuca/mysql/db:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: Concacne1!

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
